DELETE http://localhost:3003/api/blogs/695ac2130eb124ec021e2ab4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY5NWE3NjVjYjkzOWNiNzYyYTJjMjk0NCIsImlhdCI6MTc2NzU1MTE1MX0.oT3cL3-OQXNBkC5BW6GUlhcpZVIMnqJx87mL3uFJhJw